name: Torque Environment Pipeline

on:
  workflow_dispatch:

jobs:
  torque-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Start Torque Environment
      id: start-environment
      uses: QualiTorque/torque-start-environment@v1
      with:
        space: Demo
        blueprint_name: WebApp
        torque_token: ${{ secrets.TORQUE_TOKEN }}
        duration: 120
        timeout: 30
        artifacts: 'flask-app=latest/flaskapp.latest.tar.gz'
        inputs: 'PORT=8080,AWS_INSTANCE_TYPE=m5.large'

    - name: End Torque Environment
      uses: QualiTorque/torque-end-environment@v1
      with:
        space: Demo
        environment_id: ${{ steps.start-environment.outputs.environment_id }}
        torque_token: ${{ secrets.TORQUE_TOKEN }}
